OpenCBDC Transaction Processor: cbdc::parsec Namespace Reference
cbdc::parsec Namespace Reference
Namespaces
namespace agent
namespace broker
namespace directory
namespace runtime_locking_shard
namespace ticket_machine
Data Structures
struct config
Configuration parameters for a phase two system.
Enumerations
enum class load_type { transfer , erc20 }
Type of load to generate for benchmarking.
enum class runner_type { lua , evm }
Execution/transaction model.
Functions
auto split (const std::string &s, const std::string &delim) -> std::vector< std::string >
auto parse_args (int argc, char **argv) -> std::optional< std::unordered_map< std::string, std::string > >
auto read_endpoints (const std::unordered_map< std::string, std::string > &opts, const std::string &component_name) -> std::optional< std::vector< network::endpoint_t > >
auto read_cluster_endpoints (const std::unordered_map< std::string, std::string > &opts, const std::string &component_name) -> std::optional< std::vector< std::vector< network::endpoint_t > > >
auto read_config (int argc, char **argv) -> std::optional< config >
Reads the configuration parameters from the program arguments.
auto put_row (const std::shared_ptr< broker::interface > &broker, broker::key_type key, broker::value_type value, const std::function< void(bool)> &result_callback) -> bool
Asynchronously inserts the given row into the cluster.
Enumeration Type Documentation
load_type
enum class cbdc::parsec::load_type strong
Type of load to generate for benchmarking.
Enumerator
transfer
Base token transfer.
erc20
ERC20 token transfer.
Definition at line 15 of file parsec/util.hpp.
runner_type
enum class cbdc::parsec::runner_type strong
Execution/transaction model.
Enumerator
lua
Transaction semantics defined using Lua.
evm
Ethereum-style transactions using EVM.
Definition at line 23 of file parsec/util.hpp.
Function Documentation
parse_args()
auto cbdc::parsec::parse_args (int argc, char ** argv) -> std::optional<std::unordered_map<std::string, std::string>>
Definition at line 27 of file util.cpp.
References cbdc::array, cbdc::config::get_args(), and split().
Referenced by read_config().
put_row()
auto cbdc::parsec::put_row (const std::shared_ptr< broker::interface > & broker, broker::key_type key, broker::value_type value, const std::function< void(bool)> & result_callback) -> bool
Asynchronously inserts the given row into the cluster.
Parameters
broker broker to use for inserting the row.
key key at which to insert value.
value value to insert at given key.
result_callback function to call on insertion success or failure.
Returns
true if request was initiated successfully.
Definition at line 194 of file util.cpp.
References cbdc::array, and cbdc::parsec::runtime_locking_shard::write.
Referenced by cbdc::parsec::agent::runner::mint_initial_accounts().
read_cluster_endpoints()
auto cbdc::parsec::read_cluster_endpoints (const std::unordered_map< std::string, std::string > & opts, const std::string & component_name) -> std::optional<std::vector<std::vector<network::endpoint_t>>>
Definition at line 74 of file util.cpp.
References cbdc::array, and read_endpoints().
Referenced by read_config().
read_config()
auto cbdc::parsec::read_config (int argc, char ** argv) -> std::optional< config >
Reads the configuration parameters from the program arguments.
Parameters
argc number of program arguments.
argv program arguments.
Returns
configuration parametrs or std::nullopt if there was an error while parsing the arguments.
Definition at line 99 of file util.cpp.
References cbdc::array, erc20, evm, lua, cbdc::parsec::config::m_component_id, parse_args(), cbdc::logging::parse_loglevel(), read_cluster_endpoints(), read_endpoints(), cbdc::logging::trace, and transfer.
Referenced by main().
read_endpoints()
auto cbdc::parsec::read_endpoints (const std::unordered_map< std::string, std::string > & opts, const std::string & component_name) -> std::optional<std::vector<network::endpoint_t>>
Definition at line 49 of file util.cpp.
References cbdc::array, and cbdc::config::parse_ip_port().
Referenced by read_cluster_endpoints(), and read_config().
split()
auto cbdc::parsec::split (const std::string & s, const std::string & delim) -> std::vector<std::string>
Definition at line 11 of file util.cpp.
References cbdc::array.
Referenced by parse_args().